start cmd.exe /c "dotnet run -p ./VehicleTracker.TrackerService/VehicleTracker.TrackerService.csproj"
start cmd.exe /c "dotnet run -p ./VehicleTracker.TrackerManager/VehicleTracker.TrackerManager.csproj"
start cmd.exe /c "dotnet run -p ./VehicleTracker.StorageService/VehicleTracker.StorageService.csproj"
start cmd.exe /c "dotnet run -p ./VehicleTracker.AuthService/VehicleTracker.AuthService.csproj"
start cmd.exe /c "dotnet run -p ./VehicleTracker.Api/VehicleTracker.Api.csproj"
