version: '3'

services:
  vehicletracker.trackerservice:
    image: vehicletracker.trackerservice
    build:
      context: .
      dockerfile: ./VehicleTracker.TrackerService/Dockerfile
    environment:
      "RabbitMq:HostName": "rabbit"
      "RabbitMq:UserName": "rabbitmq"
      "RabbitMq:Password": "rabbitmq"
      "RabbitMq:Port": "5672"
    ports:
     - "8088:80"
    depends_on:
     - "rabbit"
  vehicletracker.authservice:
    image: vehicletracker.authservice
    build:
      context: .
      dockerfile: ./VehicleTracker.AuthService/Dockerfile
    ports:
     - "8092:80"
    environment:
      "JsClient:Domain": "http://localhost:8090"
    labels:
       NAME: "vehicletracker.authservice"
  vehicletracker.trackermanager:
    image: vehicletracker.trackermanager
    build:
      context: .
      dockerfile: ./VehicleTracker.TrackerManager/Dockerfile
    ports:
     - "8089:80"
    environment:
      "RabbitMq:HostName": "rabbit"
      "RabbitMq:UserName": "rabbitmq"
      "RabbitMq:Password": "rabbitmq"
      "RabbitMq:Port": "5672"
    depends_on:
     - "rabbit"
  vehicletracker.api:
    image: vehicletracker.api
    build:
      context: .
      dockerfile: ./VehicleTracker.Api/Dockerfile
    environment:
      "RabbitMq:HostName": "rabbit"
      "RabbitMq:UserName": "rabbitmq"
      "RabbitMq:Password": "rabbitmq"
      "RabbitMq:Port": "5672"
      "Auth:Authority": "http://vehicletracker.authservice"
      "Auth:JsAuthority": "http://localhost:8092"
      "Auth:RedirectUri": "http://localhost:8090/callback"
      "Auth:PostLogoutRedirectUri": "http://localhost:8090"
      "VehicleService": "http://vehicletracker.storageservice.fsharp/vehicles/"
      "CustomerService": "http://vehicletracker.storageservice.fsharp/customers/"
    ports:
     - "8090:80"
    depends_on:
     - "rabbit"
     - "vehicletracker.authservice"
     - "vehicletracker.storageservice.fsharp"
#  vehicletracker.storageservice:
#    image: vehicletracker.storageservice
#    build:
#      context: .
#      dockerfile: ./VehicleTracker.StorageService/Dockerfile
#    ports:
#     - "8091:80"
#    environment:
#       "ConnectionStrings:DefaultConnection": "Server=mssql;Database=VehicleDb;User Id=sa;Password=Mssqlpassword1"
#    depends_on:
#     - "mssql"
  vehicletracker.storageservice.fsharp:
    image: vehicletracker.storageservice.fsharp
    build:
      context: .
      dockerfile: ./VehicleTracker.StorageService.FSharp/Dockerfile
    ports:
     - "8093:80"
    environment:
       "ConnectionStrings:DefaultConnection": "Server=mssql;Database=VehicleDb;User Id=sa;Password=Mssqlpassword1"
    depends_on:
     - "mssql"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "Mssqlpassword1"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
